from distutils.core import setup
setup(name='dwl_multidop',
      version='2.0.0',
      description='For processing the transcranial doppler data generated on a DWL Multidop  L2.',
      long_description='See readme.txt',
      author='Matt McCormick',
      author_email='matt@mmmccormick.com',
      url='http://mmmccormick.com/#tcd_analyze',
      license='See legal.txt',
      package_dir = {'':'source'},
      packages = ['fileparsing', 'gui'],
      py_modules = ['dwl_multidop_exceptions', 'dwl_multidop'],
      requires = ['veusz', 'numpy', 'PyQt4'],
      scripts=['source/dwl_multidop.py'],
      )
